---
abstract: 'Log::Report in the lightest form'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Report-Optional
no_index:
  directory:
    - t
    - inc
requires:
  String::Print: 0.13
  Test::More: 0.86
version: 1.01
